/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include  "stm32f4_gpio_lib.h"



GPIO_InitTypeDef		myGPIO_InitSruct;

int main(void){

  myGPIO_InitSruct.Mode = GPIO_MODE_OUTPUT_PP;
  myGPIO_InitSruct.Pin  = GPIO_PIN_5;
	myGPIO_InitSruct.Pull	= GPIO_NOPULL;

	__LIB_RCC_GPIOA_CLK_ENABLE();
	LIB_GPIO_Init(GPIOA,&myGPIO_InitSruct);

	while(1){
	   for(int i =0;i< 900000;i++){}
		 LIB_GPIO_TogglePin(GPIOA,GPIO_PIN_5);

	}

}
